### ISSUE TITLE
larger images for wide screens

### ISSUE THREAD

**Issue by fabianschwarzfritz** [HanaHaus/HanaHaus-app#13]

**Comment by ssdesign** [comment]
7 large images have been added in the folder "Large_Images" inside website assets folder.

Keeping the issue open as more large images will come later.

**Comment by fabianschwarzfritz** [comment]
Thanks @ssdesign , I'll replace them all at once. Furthermore would you mind specifying which image goes to which category/part of the website? Because I can't match the names of the images in folder https://github.com/HanaHaus/HanaHaus-ux/tree/master/01_Website/Assets/Large_Images to the actual part of the website.

**Comment by ssdesign** [comment]
Hi 
I have renamed the images so you can know which image goes where.
If you have questions, let me know.
