### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by fabianschwarzfritz** [HanaHaus/HanaHaus-app#18]
I need a favicon for the HH website

**Comment by ssdesign** [comment]
Added Favicons in the assets folder for website:

HanaHaus_Fav_128.ico
HanaHaus_Fav_72.ico
HanaHaus_Fav_32.ico
HanaHaus_Fav_16.ico

**Comment by fabianschwarzfritz** [comment]
Thanks @ssdesign for the icons, I'll close the issue as soon as we implemented it.

**Comment by fabianschwarzfritz** [comment]
@ssdesign Unfortunately I could not find any icons int the assets folder (https://github.com/HanaHaus/HanaHaus-ux/tree/master/01_Website/Assets ) Sure you put them there correctly and commited the changes?

**Comment by ssdesign** [comment]
Hi,
I had not synced the repo.
You can check now.

**Comment by fabianschwarzfritz** [comment]
@ssdesign thanks! I'll start to implement it and _then_ close the issue when it's implement it. Of course, I'll assign the issue to me.

**Comment by fabianschwarzfritz** [comment]
implemented.
