### ISSUE TITLE
hover behavior on footer

### ISSUE THREAD

**Issue by gruiz17** [HanaHaus/HanaHaus-app#26]
what's the behavior when we hover over a tab/option on the footer?

**Comment by ssdesign** [comment]
Specifications updated with required details.

**Comment by fabianschwarzfritz** [comment]
Thanks @ssdesign, we'll close the issue as soon as we implemented it and I'll assign this to me.

**Comment by fabianschwarzfritz** [comment]
@ssdesign  in the specification  https://raw.githubusercontent.com/HanaHaus/HanaHaus-ux/master/01_Website/Specifications/Footer-01.png the color of the gray background of the footer is missing?

**Comment by ssdesign** [comment]
Hi Fabian,
The footer color is specified in this image:
https://raw.githubusercontent.com/HanaHaus/HanaHaus-ux/master/01_Website/Specifications/Specifications_01-01.png
